name: gank_flutter
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: "^0.3.0"
  dio: "^3.0.4"
  retrofit: any
  json_annotation: any
  logger: any
  js: ^0.6.0
  provider: ^2.0.1+1
  event_bus: ^1.1.0
  pkg_network:
    path: module/pkg_network
  plugin_dialog:
    path: module/plugin_dialog
  shared_preferences: ^0.5.6
  flutter_bugly:
    git:
      url: git://github.com/crazecoder/flutter_bugly.git
      ref: dev
  bot_toast: ^2.2.1
  cached_network_image: ^2.0.0

dev_dependencies:
  build_runner: any
  retrofit_generator: any
  json_serializable: any
  #dart server
  angel_framework: ^2.1.0
  angel_proxy: ^2.2.0
  angel_static: ^2.1.3+2

flutter:
  uses-material-design: true
  fonts:
   - family: iconfont
     fonts:
       - asset: fonts/iconfont.ttf
  assets:
    - images/flutter.png
  module:
    androidX: false
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule